"""sync schema 1

Revision ID: f17e74848220
Revises: 
Create Date: 2026-05-24 11:18:07.200738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17e74848220'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('covered_areas', sa.JSON(), nullable=False),
    sa.Column('postcode_prefixes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_zones_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_zones_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_zones_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_delivery_zones_town'), ['town'], unique=False)

    op.create_table('processed_webhook_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_webhook_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_processed_webhook_events_provider'), ['provider'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('store_branches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('plot_number', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('allows_delivery', sa.Boolean(), nullable=False),
    sa.Column('allows_pickup', sa.Boolean(), nullable=False),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_branches_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_branches_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_branches_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_branches_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_branches_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_branches_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_branches_town'), ['town'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=150), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('branch_delivery_zones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_zone_id', sa.BigInteger(), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('free_delivery_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_delivery_minutes', sa.Integer(), nullable=True),
    sa.Column('max_delivery_distance_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('supports_same_day_delivery', sa.Boolean(), nullable=False),
    sa.Column('supports_scheduled_delivery', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'delivery_zone_id', name='uq_branch_delivery_zone')
    )
    with op.batch_alter_table('branch_delivery_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_delivery_zones_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_delivery_zones_delivery_zone_id'), ['delivery_zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_delivery_zones_is_active'), ['is_active'], unique=False)

    op.create_table('branch_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uq_branch_product')
    )
    with op.batch_alter_table('branch_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_products_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_products_product_id'), ['product_id'], unique=False)

    op.create_table('branch_staff',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_staff_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_staff_user_id'), ['user_id'], unique=False)

    op.create_table('carts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_carts_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_user_id'), ['user_id'], unique=False)

    op.create_table('courier_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courier_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courier_profiles_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_courier_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('customer_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('default_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_profiles_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_profiles_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAYMENT_PROCESSING', 'PAID', 'FULFILLMENT_PENDING', 'PROCESSING', 'READY_FOR_PICKUP', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'PAYMENT_FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('is_delivery', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payment_processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('delivery_fee >= 0', name='ck_order_delivery_fee_non_negative'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_order_discount_non_negative'),
    sa.CheckConstraint('grand_total >= 0', name='ck_order_grand_total_non_negative'),
    sa.CheckConstraint('subtotal_amount >= 0', name='ck_order_subtotal_non_negative'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_order_tax_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_searches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('query', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_searches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_searches_query'), ['query'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_sku'), ['sku'], unique=True)

    op.create_table('staff_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_profiles_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('branch_product_variants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('branch_product_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('allows_pickup', sa.Boolean(), nullable=False),
    sa.Column('allows_delivery', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_product_id'], ['branch_products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_product_id', 'variant_id', name='uq_branch_variant')
    )
    with op.batch_alter_table('branch_product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_product_variants_branch_product_id'), ['branch_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_product_variants_variant_id'), ['variant_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('courier_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('UNASSIGNED', 'ASSIGNED', 'ACCEPTED', 'ARRIVED_AT_PICKUP', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED', 'RETURNED', name='deliverystatus'), nullable=False),
    sa.Column('delivery_zone_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_zone_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_fee_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_address_snapshot', sa.JSON(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('out_for_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_delivery_zone_id'), ['delivery_zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_deliveries_status'), ['status'], unique=False)

    op.create_table('order_addresses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('area_normalized', sa.String(length=100), nullable=False),
    sa.Column('plot_number', sa.String(length=100), nullable=False),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    with op.batch_alter_table('order_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_addresses_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_addresses_area_normalized'), ['area_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_addresses_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_addresses_region'), ['region'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('sku_snapshot', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY_FOR_PICKUP', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED', name='orderitemstatus'), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_status'), ['status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', name='paymentprovider'), nullable=False),
    sa.Column('provider_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('provider_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'REQUIRES_ACTION', 'PROCESSING', 'AUTHORIZED', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('failure_code', sa.String(length=255), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_provider_checkout_session_id'), ['provider_checkout_session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_provider_payment_intent_id'), ['provider_payment_intent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('product_promotions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_product_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('promotion_type', sa.Enum('PERCENTAGE', 'FIXED', name='promotiontype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_product_id'], ['branch_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_promotions_branch_product_id'), ['branch_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_promotions_is_active'), ['is_active'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_cart_item_quantity_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.ForeignKeyConstraint(['branch_variant_id'], ['branch_product_variants.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'variant_id', 'branch_id', name='uq_cart_variant_branch')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_branch_variant_id'), ['branch_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_variant_id'), ['variant_id'], unique=False)

    op.create_table('delivery_otps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('courier_id', sa.BigInteger(), nullable=True),
    sa.Column('otp_type', sa.Enum('PICKUP', 'DELIVERY', name='deliveryotptype'), nullable=False),
    sa.Column('otp_code_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_invalidated', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['store_branches.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'otp_type', 'is_verified', 'is_invalidated', name='uq_active_order_otp')
    )
    with op.batch_alter_table('delivery_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_otps_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_otps_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_otps_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_otps_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_otps_otp_type'), ['otp_type'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.CheckConstraint('reserved_quantity <= quantity', name='ck_inventory_reserved_lte_quantity'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_non_negative'),
    sa.ForeignKeyConstraint(['branch_variant_id'], ['branch_product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_branch_variant_id'), ['branch_variant_id'], unique=True)

    op.create_table('inventory_reservations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('inventory_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'COMMITTED', 'RELEASED', 'EXPIRED', name='inventoryreservationstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_reservation_quantity_positive'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'inventory_id', name='uq_inventory_reservation_order_inventory')
    )
    with op.batch_alter_table('inventory_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reservations_inventory_id'), ['inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reservations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reservations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_order_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_expires_at'))

    op.drop_table('inventory_reservations')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_branch_variant_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('delivery_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_otps_otp_type'))
        batch_op.drop_index(batch_op.f('ix_delivery_otps_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_otps_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_otps_courier_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_otps_branch_id'))

    op.drop_table('delivery_otps')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_variant_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_branch_variant_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_branch_id'))

    op.drop_table('cart_items')
    with op.batch_alter_table('product_promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_promotions_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_promotions_branch_product_id'))

    op.drop_table('product_promotions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_checkout_session_id'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_idempotency_key'))

    op.drop_table('payments')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_status'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('order_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_addresses_region'))
        batch_op.drop_index(batch_op.f('ix_order_addresses_city'))
        batch_op.drop_index(batch_op.f('ix_order_addresses_area_normalized'))
        batch_op.drop_index(batch_op.f('ix_order_addresses_area'))

    op.drop_table('order_addresses')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_deliveries_order_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_delivery_zone_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_courier_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_branch_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('branch_product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_product_variants_variant_id'))
        batch_op.drop_index(batch_op.f('ix_branch_product_variants_branch_product_id'))

    op.drop_table('branch_product_variants')
    op.drop_table('user_roles')
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_profiles_public_id'))

    op.drop_table('staff_profiles')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_sku'))
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_searches_query'))
        batch_op.drop_index(batch_op.f('ix_product_searches_created_at'))

    op.drop_table('product_searches')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_public_id'))
        batch_op.drop_index(batch_op.f('ix_orders_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_orders_branch_id'))

    op.drop_table('orders')
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_profiles_public_id'))
        batch_op.drop_index(batch_op.f('ix_customer_profiles_city'))

    op.drop_table('customer_profiles')
    with op.batch_alter_table('courier_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courier_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_courier_profiles_public_id'))

    op.drop_table('courier_profiles')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carts_user_id'))
        batch_op.drop_index(batch_op.f('ix_carts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_carts_public_id'))
        batch_op.drop_index(batch_op.f('ix_carts_is_active'))
        batch_op.drop_index(batch_op.f('ix_carts_expires_at'))
        batch_op.drop_index(batch_op.f('ix_carts_created_at'))

    op.drop_table('carts')
    with op.batch_alter_table('branch_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_branch_staff_branch_id'))

    op.drop_table('branch_staff')
    with op.batch_alter_table('branch_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_branch_products_branch_id'))

    op.drop_table('branch_products')
    with op.batch_alter_table('branch_delivery_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_delivery_zones_is_active'))
        batch_op.drop_index(batch_op.f('ix_branch_delivery_zones_delivery_zone_id'))
        batch_op.drop_index(batch_op.f('ix_branch_delivery_zones_branch_id'))

    op.drop_table('branch_delivery_zones')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_email'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_device_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_branch_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('store_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_branches_town'))
        batch_op.drop_index(batch_op.f('ix_store_branches_postal_code'))
        batch_op.drop_index(batch_op.f('ix_store_branches_name'))
        batch_op.drop_index(batch_op.f('ix_store_branches_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_store_branches_is_active'))
        batch_op.drop_index(batch_op.f('ix_store_branches_city'))
        batch_op.drop_index(batch_op.f('ix_store_branches_area'))

    op.drop_table('store_branches')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    with op.batch_alter_table('processed_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_webhook_events_provider'))
        batch_op.drop_index(batch_op.f('ix_processed_webhook_events_event_id'))

    op.drop_table('processed_webhook_events')
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_zones_town'))
        batch_op.drop_index(batch_op.f('ix_delivery_zones_name'))
        batch_op.drop_index(batch_op.f('ix_delivery_zones_is_active'))
        batch_op.drop_index(batch_op.f('ix_delivery_zones_city'))

    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
